### ISSUE TITLE
response of event that is sent is OK, but includes an "invalid: bad event id" 

### ISSUE THREAD

**Issue by anasfik** [nostr-protocol/nostr#147]
hello, 
I'am sending some data to [wss://relay.damus.io](wss://relay.damus.io), basically this:
```json
[
	"EVENT",
	{
		"id": "a89ce1f028f0735fb0e650acbed94f15aa34dac35c1a4ab76e1a9bdeaed7c874",
		"kind": 0,
		"content": {
			"name": "v1888888888888888"
		},
		"sig": "168c0ffd80a1994775fe01c0128cefad201a777073ea1d9658585a7b919895fa949ddd2c3512eed3ca781210ee0d370ec62fb2d644bf084affc58a441923d167",
		"pubkey": "02e0918d1c1291282839335aedf55170a07ac590a1308c7531c867d57822b41d",
		"created_at": 1680129089,
		"tags": []
	}
]
```

the WebSocket triggers it and sends an "OK" event to me, but with "invalid: bad event id":
```dart
[
	"OK",
	"a89ce1f028f0735fb0e650acbed94f15aa34dac35c1a4ab76e1a9bdeaed7c874",
	false,
	"invalid: bad event id"
]
```

from the NIPs docs, "OK" means that an event is handled successfully, but si what about the error message that I'm facing ?

**Comment by fiatjaf** [comment]
`OK` can be `true` or `false`. In this case it was `false`. The message says why it was `false`.

You can paste your event on https://nak.nostr.com/ to see if it helps debugging what is wrong with your event id, but I can tell you from here that the issue is your `.content` field. It must be a string.
